INSERT INTO `lsc_metadata` (`meta_name`, `meta_type`, `meta_code`, `meta_text`, `is_active`) VALUES
('resource', 'columnheading', 'username', 'short id', 1),
('resource', 'columnheading', 'firstname', 'first name', 1),
('resource', 'columnheading', 'lastname', 'last name', 1),
('resource', 'columnheading', 'email', 'email address', 1),
('resource', 'columnheading', 'city', 'city', 1),
('resource', 'columnheading', 'country', 'country', 1),
('resource', 'columnheading', 'timezone', 'timezone', 1),
('resource', 'columnheading', 'profile_field_plm', 'pl manager short id', 1),
('resource', 'columnheading', 'profile_field_productline', 'product line', 1),
('resource', 'columnheading', 'profile_field_empstatus', 'employment status', 1),
('resource', 'columnheading', 'profile_field_sapmanager', 'resource manager short id', 1),
('resource', 'columnheading', 'profile_field_workregion', 'work region', 1),
('resource', 'columnheading', 'profile_field_plmanager', 'is the resource a plm?', 1),
('resource', 'columnheading', 'profile_field_sdmanager', 'is the resource a sdm?', 1),
('resource', 'columnheading', 'profile_field_ktpm', 'is the user a ktpm?', 1),
('resource', 'timezone', '+5.5', 'India Standard Time (GMT +05:30)', 1),
('resource', 'timezone', '0', 'Western European Time (GMT +00:00)', 1),
('resource', 'timezone', '-8', 'Pacific Time (GMT -08:00)', 1),
('resource', 'timezone', '-6', 'Central Standard Time (GMT -06:00)', 1),
('resource', 'timezone', '-5', 'Eastern Time (GMT -05:00)', 1),
('resource', 'productline', '1', 'Billing', 1),
('resource', 'productline', '2', 'Business Excellence', 1),
('resource', 'productline', '3', 'CBIFT', 1),
('resource', 'productline', '4', 'Claims', 1),
('resource', 'productline', '5', 'Client Server', 1),
('resource', 'productline', '6', 'Clinical Systems', 1),
('resource', 'productline', '7', 'Collaborative', 1),
('resource', 'productline', '8', 'Controls', 1),
('resource', 'productline', '9', 'Cross Functional Services', 1),
('resource', 'productline', '10', 'D & I Canada', 1),
('resource', 'productline', '11', 'DBA', 1),
('resource', 'productline', '12', 'DMO', 1),
('resource', 'productline', '13', 'EAI', 1),
('resource', 'productline', '14', 'Engineering Services', 1),
('resource', 'productline', '15', 'ETS', 1),
('resource', 'productline', '16', 'Financial Management', 1),
('resource', 'productline', '17', 'GAMO', 1),
('resource', 'productline', '18', 'GESM', 1),
('resource', 'productline', '19', 'GSS', 1),
('resource', 'productline', '20', 'JOL', 1),
('resource', 'productline', '21', 'K5', 1),
('resource', 'productline', '22', 'K6', 1),
('resource', 'productline', '23', 'Mediation', 1),
('resource', 'productline', '24', 'MNS', 1),
('resource', 'productline', '25', 'Oracle Support', 1),
('resource', 'productline', '26', 'Order Management', 1),
('resource', 'productline', '27', 'PAT Admins', 1),
('resource', 'productline', '28', 'PE Mainframe', 1),
('resource', 'productline', '29', 'PE Unix', 1),
('resource', 'productline', '30', 'PeopleSoft', 1),
('resource', 'productline', '31', 'PM', 1),
('resource', 'productline', '32', 'Production Integration', 1),
('resource', 'productline', '33', 'Regression Testing', 1),
('resource', 'productline', '34', 'Release Control', 1),
('resource', 'productline', '35', 'RIO', 1),
('resource', 'productline', '36', 'Service Delivery', 1),
('resource', 'productline', '37', 'Service Desk', 1),
('resource', 'productline', '38', 'Siebel', 1),
('resource', 'productline', '39', 'Storage & Backup', 1),
('resource', 'productline', '40', 'UTS-TUW', 1),
('resource', 'productline', '41', 'UTS-AUW', 1),
('resource', 'productline', '42', 'Wintel', 1),
('resource', 'productline', '43', 'After Sales and Quality', 1),
('resource', 'productline', '44', 'Business Systems', 1),
('resource', 'productline', '45', 'Manufacturing', 1),
('resource', 'productline', '46', 'Mgmt', 1),
('resource', 'productline', '47', 'UCC', 1),
('resource', 'productline', '48', 'Servicing Team', 1),
('resource', 'productline', '49', 'Application Operations', 1),
('resource', 'productline', '50', 'Provisioning', 1),
('resource', 'empstatus', '1', 'Employee', 1),
('resource', 'empstatus', '2', 'Sub-con', 1),
('resource', 'empstatus', '3', 'Vendor', 1),
('resource', 'workregion', '0', 'EMEA', 1),
('resource', 'workregion', '1', 'NA', 1),
('resource', 'workregion', '2', 'AUST', 1),
('resource', 'workregion', '3', 'MULTIPLE', 1),
('resource', 'workregion', '4', 'IND', 1),
('resource', 'plm', '0', 'No', 1),
('resource', 'plm', '1', 'Yes', 1),
('resource', 'sdm', '0', 'No', 1),
('resource', 'sdm', '1', 'Yes', 1),
('resource', 'ktpm', '0', 'No', 1),
('resource', 'ktpm', '1', 'Yes', 1),
('resource', 'country', 'AF', 'Afghanistan', 1),
('resource', 'country', 'AX', 'Aland Islands', 1),
('resource', 'country', 'AL', 'Albania', 1),
('resource', 'country', 'DZ', 'Algeria', 1),
('resource', 'country', 'AS', 'American Samoa', 1),
('resource', 'country', 'AD', 'Andorra', 1),
('resource', 'country', 'AO', 'Angola', 1),
('resource', 'country', 'AI', 'Anguilla', 1),
('resource', 'country', 'AQ', 'Antarctica', 1),
('resource', 'country', 'AG', 'Antigua And Barbuda', 1),
('resource', 'country', 'AR', 'Argentina', 1),
('resource', 'country', 'AM', 'Armenia', 1),
('resource', 'country', 'AW', 'Aruba', 1),
('resource', 'country', 'AU', 'Australia', 1),
('resource', 'country', 'AT', 'Austria', 1),
('resource', 'country', 'AZ', 'Azerbaijan', 1),
('resource', 'country', 'BS', 'Bahamas', 1),
('resource', 'country', 'BH', 'Bahrain', 1),
('resource', 'country', 'BD', 'Bangladesh', 1),
('resource', 'country', 'BB', 'Barbados', 1),
('resource', 'country', 'BY', 'Belarus', 1),
('resource', 'country', 'BE', 'Belgium', 1),
('resource', 'country', 'BZ', 'Belize', 1),
('resource', 'country', 'BJ', 'Benin', 1),
('resource', 'country', 'BM', 'Bermuda', 1),
('resource', 'country', 'BT', 'Bhutan', 1),
('resource', 'country', 'BO', 'Bolivia', 1),
('resource', 'country', 'BA', 'Bosnia And Herzegovina', 1),
('resource', 'country', 'BW', 'Botswana', 1),
('resource', 'country', 'BV', 'Bouvet Island', 1),
('resource', 'country', 'BR', 'Brazil', 1),
('resource', 'country', 'IO', 'British Indian Ocean Territory', 1),
('resource', 'country', 'BN', 'Brunei Darussalam', 1),
('resource', 'country', 'BG', 'Bulgaria', 1),
('resource', 'country', 'BF', 'Burkina Faso', 1),
('resource', 'country', 'BI', 'Burundi', 1),
('resource', 'country', 'KH', 'Cambodia', 1),
('resource', 'country', 'CM', 'Cameroon', 1),
('resource', 'country', 'CA', 'Canada', 1),
('resource', 'country', 'CV', 'Cape Verde', 1),
('resource', 'country', 'KY', 'Cayman Islands', 1),
('resource', 'country', 'CF', 'Central African Republic', 1),
('resource', 'country', 'TD', 'Chad', 1),
('resource', 'country', 'CL', 'Chile', 1),
('resource', 'country', 'CN', 'China', 1),
('resource', 'country', 'CX', 'Christmas Island', 1),
('resource', 'country', 'CC', 'Cocos (Keeling) Islands', 1),
('resource', 'country', 'CO', 'Colombia', 1),
('resource', 'country', 'KM', 'Comoros', 1),
('resource', 'country', 'CG', 'Congo', 1),
('resource', 'country', 'CD', 'Congo - The Democratic Republic Of The', 1),
('resource', 'country', 'CK', 'Cook Islands', 1),
('resource', 'country', 'CR', 'Costa Rica', 1),
('resource', 'country', 'CI', 'Cote D''Ivoire', 1),
('resource', 'country', 'HR', 'Croatia', 1),
('resource', 'country', 'CU', 'Cuba', 1),
('resource', 'country', 'CY', 'Cyprus', 1),
('resource', 'country', 'CZ', 'Czech Republic', 1),
('resource', 'country', 'DK', 'Denmark', 1),
('resource', 'country', 'DJ', 'Djibouti', 1),
('resource', 'country', 'DM', 'Dominica', 1),
('resource', 'country', 'DO', 'Dominican Republic', 1),
('resource', 'country', 'EC', 'Ecuador', 1),
('resource', 'country', 'EG', 'Egypt', 1),
('resource', 'country', 'SV', 'El Salvador', 1),
('resource', 'country', 'GQ', 'Equatorial Guinea', 1),
('resource', 'country', 'ER', 'Eritrea', 1),
('resource', 'country', 'EE', 'Estonia', 1),
('resource', 'country', 'ET', 'Ethiopia', 1),
('resource', 'country', 'FK', 'Falkland Islands (Malvinas)', 1),
('resource', 'country', 'FO', 'Faroe Islands', 1),
('resource', 'country', 'FJ', 'Fiji', 1),
('resource', 'country', 'FI', 'Finland', 1),
('resource', 'country', 'FR', 'France', 1),
('resource', 'country', 'GF', 'French Guiana', 1),
('resource', 'country', 'PF', 'French Polynesia', 1),
('resource', 'country', 'TF', 'French Southern Territories', 1),
('resource', 'country', 'GA', 'Gabon', 1),
('resource', 'country', 'GM', 'Gambia', 1),
('resource', 'country', 'GE', 'Georgia', 1),
('resource', 'country', 'DE', 'Germany', 1),
('resource', 'country', 'GH', 'Ghana', 1),
('resource', 'country', 'GI', 'Gibraltar', 1),
('resource', 'country', 'GR', 'Greece', 1),
('resource', 'country', 'GL', 'Greenland', 1),
('resource', 'country', 'GD', 'Grenada', 1),
('resource', 'country', 'GP', 'Guadeloupe', 1),
('resource', 'country', 'GU', 'Guam', 1),
('resource', 'country', 'GT', 'Guatemala', 1),
('resource', 'country', 'GG', 'Guernsey', 1),
('resource', 'country', 'GN', 'Guinea', 1),
('resource', 'country', 'GW', 'Guinea-Bissau', 1),
('resource', 'country', 'GY', 'Guyana', 1),
('resource', 'country', 'HT', 'Haiti', 1),
('resource', 'country', 'HM', 'Heard Island And Mcdonald Islands', 1),
('resource', 'country', 'VA', 'Holy See (Vatican City State)', 1),
('resource', 'country', 'HN', 'Honduras', 1),
('resource', 'country', 'HK', 'Hong Kong', 1),
('resource', 'country', 'HU', 'Hungary', 1),
('resource', 'country', 'IS', 'Iceland', 1),
('resource', 'country', 'IN', 'India', 1),
('resource', 'country', 'ID', 'Indonesia', 1),
('resource', 'country', 'IR', 'Iran - Islamic Republic Of', 1),
('resource', 'country', 'IQ', 'Iraq', 1),
('resource', 'country', 'IE', 'Ireland', 1),
('resource', 'country', 'IM', 'Isle Of Man', 1),
('resource', 'country', 'IL', 'Israel', 1),
('resource', 'country', 'IT', 'Italy', 1),
('resource', 'country', 'JM', 'Jamaica', 1),
('resource', 'country', 'JP', 'Japan', 1),
('resource', 'country', 'JE', 'Jersey', 1),
('resource', 'country', 'JO', 'Jordan', 1),
('resource', 'country', 'KZ', 'Kazakhstan', 1),
('resource', 'country', 'KE', 'Kenya', 1),
('resource', 'country', 'KI', 'Kiribati', 1),
('resource', 'country', 'KP', 'Korea - Democratic People''s Republic Of', 1),
('resource', 'country', 'KR', 'Korea - Republic Of', 1),
('resource', 'country', 'KW', 'Kuwait', 1),
('resource', 'country', 'KG', 'Kyrgyzstan', 1),
('resource', 'country', 'LA', 'Lao People''s Democratic Republic', 1),
('resource', 'country', 'LV', 'Latvia', 1),
('resource', 'country', 'LB', 'Lebanon', 1),
('resource', 'country', 'LS', 'Lesotho', 1),
('resource', 'country', 'LR', 'Liberia', 1),
('resource', 'country', 'LY', 'Libyan Arab Jamahiriya', 1),
('resource', 'country', 'LI', 'Liechtenstein', 1),
('resource', 'country', 'LT', 'Lithuania', 1),
('resource', 'country', 'LU', 'Luxembourg', 1),
('resource', 'country', 'MO', 'Macao', 1),
('resource', 'country', 'MK', 'Macedonia - The Former Yugoslav Republic Of', 1),
('resource', 'country', 'MG', 'Madagascar', 1),
('resource', 'country', 'MW', 'Malawi', 1),
('resource', 'country', 'MY', 'Malaysia', 1),
('resource', 'country', 'MV', 'Maldives', 1),
('resource', 'country', 'ML', 'Mali', 1),
('resource', 'country', 'MT', 'Malta', 1),
('resource', 'country', 'MH', 'Marshall Islands', 1),
('resource', 'country', 'MQ', 'Martinique', 1),
('resource', 'country', 'MR', 'Mauritania', 1),
('resource', 'country', 'MU', 'Mauritius', 1),
('resource', 'country', 'YT', 'Mayotte', 1),
('resource', 'country', 'MX', 'Mexico', 1),
('resource', 'country', 'FM', 'Micronesia - Federated States Of', 1),
('resource', 'country', 'MD', 'Moldova - Republic Of', 1),
('resource', 'country', 'MC', 'Monaco', 1),
('resource', 'country', 'MN', 'Mongolia', 1),
('resource', 'country', 'ME', 'Montenegro', 1),
('resource', 'country', 'MS', 'Montserrat', 1),
('resource', 'country', 'MA', 'Morocco', 1),
('resource', 'country', 'MZ', 'Mozambique', 1),
('resource', 'country', 'MM', 'Myanmar', 1),
('resource', 'country', 'NA', 'Namibia', 1),
('resource', 'country', 'NR', 'Nauru', 1),
('resource', 'country', 'NP', 'Nepal', 1),
('resource', 'country', 'NL', 'Netherlands', 1),
('resource', 'country', 'AN', 'Netherlands Antilles', 1),
('resource', 'country', 'NC', 'New Caledonia', 1),
('resource', 'country', 'NZ', 'New Zealand', 1),
('resource', 'country', 'NI', 'Nicaragua', 1),
('resource', 'country', 'NE', 'Niger', 1),
('resource', 'country', 'NG', 'Nigeria', 1),
('resource', 'country', 'NU', 'Niue', 1),
('resource', 'country', 'NF', 'Norfolk Island', 1),
('resource', 'country', 'MP', 'Northern Mariana Islands', 1),
('resource', 'country', 'NO', 'Norway', 1),
('resource', 'country', 'OM', 'Oman', 1),
('resource', 'country', 'PK', 'Pakistan', 1),
('resource', 'country', 'PW', 'Palau', 1),
('resource', 'country', 'PS', 'Palestinian Territory - Occupied', 1),
('resource', 'country', 'PA', 'Panama', 1),
('resource', 'country', 'PG', 'Papua New Guinea', 1),
('resource', 'country', 'PY', 'Paraguay', 1),
('resource', 'country', 'PE', 'Peru', 1),
('resource', 'country', 'PH', 'Philippines', 1),
('resource', 'country', 'PN', 'Pitcairn', 1),
('resource', 'country', 'PL', 'Poland', 1),
('resource', 'country', 'PT', 'Portugal', 1),
('resource', 'country', 'PR', 'Puerto Rico', 1),
('resource', 'country', 'QA', 'Qatar', 1),
('resource', 'country', 'RE', 'Reunion', 1),
('resource', 'country', 'RO', 'Romania', 1),
('resource', 'country', 'RU', 'Russian Federation', 1),
('resource', 'country', 'RW', 'Rwanda', 1),
('resource', 'country', 'BL', 'Saint Barthelemy', 1),
('resource', 'country', 'SH', 'Saint Helena', 1),
('resource', 'country', 'KN', 'Saint Kitts And Nevis', 1),
('resource', 'country', 'LC', 'Saint Lucia', 1),
('resource', 'country', 'MF', 'Saint Martin', 1),
('resource', 'country', 'PM', 'Saint Pierre And Miquelon', 1),
('resource', 'country', 'VC', 'Saint Vincent And The Grenadines', 1),
('resource', 'country', 'WS', 'Samoa', 1),
('resource', 'country', 'SM', 'San Marino', 1),
('resource', 'country', 'ST', 'Sao Tome And Principe', 1),
('resource', 'country', 'SA', 'Saudi Arabia', 1),
('resource', 'country', 'SN', 'Senegal', 1),
('resource', 'country', 'RS', 'Serbia', 1),
('resource', 'country', 'SC', 'Seychelles', 1),
('resource', 'country', 'SL', 'Sierra Leone', 1),
('resource', 'country', 'SG', 'Singapore', 1),
('resource', 'country', 'SK', 'Slovakia', 1),
('resource', 'country', 'SI', 'Slovenia', 1),
('resource', 'country', 'SB', 'Solomon Islands', 1),
('resource', 'country', 'SO', 'Somalia', 1),
('resource', 'country', 'ZA', 'South Africa', 1),
('resource', 'country', 'GS', 'South Georgia And The South Sandwich Islands', 1),
('resource', 'country', 'ES', 'Spain', 1),
('resource', 'country', 'LK', 'Sri Lanka', 1),
('resource', 'country', 'SD', 'Sudan', 1),
('resource', 'country', 'SR', 'Suriname', 1),
('resource', 'country', 'SJ', 'Svalbard And Jan Mayen', 1),
('resource', 'country', 'SZ', 'Swaziland', 1),
('resource', 'country', 'SE', 'Sweden', 1),
('resource', 'country', 'CH', 'Switzerland', 1),
('resource', 'country', 'SY', 'Syrian Arab Republic', 1),
('resource', 'country', 'TW', 'Taiwan - Province Of China', 1),
('resource', 'country', 'TJ', 'Tajikistan', 1),
('resource', 'country', 'TZ', 'Tanzania - United Republic Of', 1),
('resource', 'country', 'TH', 'Thailand', 1),
('resource', 'country', 'TL', 'Timor-Leste', 1),
('resource', 'country', 'TG', 'Togo', 1),
('resource', 'country', 'TK', 'Tokelau', 1),
('resource', 'country', 'TO', 'Tonga', 1),
('resource', 'country', 'TT', 'Trinidad And Tobago', 1),
('resource', 'country', 'TN', 'Tunisia', 1),
('resource', 'country', 'TR', 'Turkey', 1),
('resource', 'country', 'TM', 'Turkmenistan', 1),
('resource', 'country', 'TC', 'Turks And Caicos Islands', 1),
('resource', 'country', 'TV', 'Tuvalu', 1),
('resource', 'country', 'UG', 'Uganda', 1),
('resource', 'country', 'UA', 'Ukraine', 1),
('resource', 'country', 'AE', 'United Arab Emirates', 1),
('resource', 'country', 'GB', 'United Kingdom', 1),
('resource', 'country', 'US', 'United States', 1),
('resource', 'country', 'UM', 'United States Minor Outlying Islands', 1),
('resource', 'country', 'UY', 'Uruguay', 1),
('resource', 'country', 'UZ', 'Uzbekistan', 1),
('resource', 'country', 'VU', 'Vanuatu', 1),
('resource', 'country', 'VE', 'Venezuela', 1),
('resource', 'country', 'VN', 'Viet Nam', 1),
('resource', 'country', 'VG', 'Virgin Islands - British', 1),
('resource', 'country', 'VI', 'Virgin Islands - U.S.', 1),
('resource', 'country', 'WF', 'Wallis And Futuna', 1),
('resource', 'country', 'EH', 'Western Sahara', 1),
('resource', 'country', 'YE', 'Yemen', 1),
('resource', 'country', 'ZM', 'Zambia', 1),
('resource', 'country', 'ZW', 'Zimbabwe', 1),
('resource', 'productline', '51', 'PSP_APMO', 1),
('resource', 'productline', '52', 'Ebusiness', 1),
('resource', 'productline', '53', 'Foremost', 1),
('role', 'targetdate', '5', '5 days', 1),
('role', 'targetdate', '10', '10 days', 1),
('role', 'targetdate', '15', '15 days', 1),
('role', 'targetdate', '20', '20 days', 1),
('role', 'targetdate', '25', '25 days', 1),
('role', 'targetdate', '30', '30 days', 1),
('role', 'targetdate', '35', '35 days', 1),
('role', 'targetdate', '40', '40 days', 1),
('role', 'targetdate', '45', '45 days', 1),
('role', 'targetdate', '50', '50 days', 1),
('role', 'targetdate', '55', '55 days', 1),
('role', 'targetdate', '60', '60 days', 1),
('role', 'targetdate', '65', '65 days', 1),
('role', 'targetdate', '70', '70 days', 1),
('role', 'targetdate', '75', '75 days', 1),
('role', 'targetdate', '80', '80 days', 1),
('role', 'targetdate', '85', '85 days', 1),
('role', 'targetdate', '90', '90 days', 1),
('role','PL manager designation','1','Functional Manager'),
('role','PL manager designation','2','Account Lead'),
('role','PL manager designation','3','Line Of Service PE'),
('resource', 'timezone', '+4.5', 'Afghanistan Time (GMT +04:30)', 1),
('resource', 'timezone', '-9', 'Alaska Time (GMT -09:00)', 1),
('resource', 'timezone', '+3', 'Arabian Standard Time (GMT +03:00)', 1),
('resource', 'timezone', '-3', 'Argentina Time (GMT -03:00)', 1),
('resource', 'timezone', '-4', 'Atlantic Time (GMT -04:00)', 1),
('resource', 'timezone', '+9.5', 'Australian Central Standard Time (GMT +09:30)', 1),
('resource', 'timezone', '+10', 'Australian Eastern Standard Time (GMT +10:00)', 1),
('resource', 'timezone', '+8', 'Australian Western Standard Time (GMT +08:00)', 1),
('resource', 'timezone', '+6', 'Bangladesh Time (GMT +06:00)', 1),
('resource', 'timezone', '-3.01', 'Brazil (Sao Paulo)(GMT -03:00)', 1),
('resource', 'timezone', '-1', 'Cape Verde Time (GMT -01:00)', 1),
('resource', 'timezone', '+10.01', 'Chamorro Standard Time (GMT +10:00)', 1),
('resource', 'timezone', '-4.01', 'Chile (Santiago) (GMT -04:00)', 1),
('resource', 'timezone', '+8.01', 'China Standard Time (GMT +08:00)', 1),
('resource', 'timezone', '-5.01', 'Colombia Time (GMT -05:00)', 1),
('resource', 'timezone', '+3.01', 'East Africa Time (GMT +03:00)', 1),
('resource', 'timezone', '+2', 'Eastern European Time (GMT +02:00)', 1),
('resource', 'timezone', '-2', 'Fernando de Noronha Time (GMT -02:00)', 1),
('resource', 'timezone', '+12', 'Fuji Time (GMT +12:00)', 1),
('resource', 'timezone', '+2.01', 'Finland Time (GMT +02:00)', 1),
('resource', 'timezone', '+1', 'France Time (GMT +01:00)', 1),
('resource', 'timezone', '+4', 'Georgia Time (GMT +04:00)', 1),
('resource', 'timezone', '+1.01', 'Germany Time (GMT +01:00)', 1),
('resource', 'timezone', '-12', 'GMT -12:00 (GMT -12:00)', 1),
('resource', 'timezone', '-3.02', 'Greenland (Godthab) (GMT -03:00)', 1),
('resource', 'timezone', '+4.01', 'Gulf Standard Time (GMT +04:00)', 1),
('resource', 'timezone', '-10', 'Hawaii - Aleutian Standard Time (GMT -10:00)', 1),
('resource', 'timezone', '+7', 'Indochina Time (GMT +07:00)', 1),
('resource', 'timezone', '+3.5', 'Iran Time (GMT +03:30)', 1),
('resource', 'timezone', '+9', 'Irkutsk Time (GMT +09:00)', 1),
('resource', 'timezone', '+2.02', 'Israel Time (GMT +02:00)', 1),
('resource', 'timezone', '+9.01', 'Japan Standard Time (GMT +09:00)', 1),
('resource', 'timezone', '+9.02', 'Korean Standard Time (GMT +09:00)', 1),
('resource', 'timezone', '+8.02', 'Krasnoyarsk Time (GMT +08:00)', 1),
('resource', 'timezone', '+12.01', 'Magadan Time (GMT +12:00)', 1),
('resource', 'timezone', '+4.02', 'Moscow Standard Time (GMT +04:00)', 1),
('resource', 'timezone', '-7', 'Mountain Standard Time (GMT -07:00)', 1),
('resource', 'timezone', '+6.5', 'Myanmar Time (GMT +06:30)', 1),
('resource', 'timezone', '+5.75', 'Nepal Time (GMT +05:45)', 1),
('resource', 'timezone', '+12.02', 'New Zealand Time (GMT +12:00)', 1),
('resource', 'timezone', '-3.5', 'Newfoundland Time (GMT -03:30)', 1),
('resource', 'timezone', '+7.01', 'Novosibirsk Time (GMT +07:00)', 1),
('resource', 'timezone', '+5', 'Pakistan Time (GMT +05:00)', 1),
('resource', 'timezone', '-1.01', 'Portugal(Azores) (GMT -01:00)', 1),
('resource', 'timezone', '+2.03', 'Romania Time (GMT +02:00)', 1),
('resource', 'timezone', '-11', 'Samoa Standard Time (GMT -11:00)', 1),
('resource', 'timezone', '+1.02', 'Serbia Time (GMT +01:00)', 1),
('resource', 'timezone', '+8.03', 'Singapore Standard Time (GMT +08:00)', 1),
('resource', 'timezone', '+2.04', 'South Africa Standard Time (GMT +02:00)', 1),
('resource', 'timezone', '+8.04', 'Taiwan Time (GMT +08:00)', 1),
('resource', 'timezone', '+13', 'Tonga Time (GMT +13:00)', 1),
('resource', 'timezone', '+2.05', 'Turkey Time (GMT +02:00)', 1),
('resource', 'timezone', '0.01', 'United Kingdom Time (GMT +00:00)', 1),
('resource', 'timezone', '-4.5', 'Venezuela Time (GMT -04:30)', 1),
('resource', 'timezone', '+11', 'Vladivostok Time (GMT +11:00)', 1),
('resource', 'timezone', '+1.04', 'West Africa Time (GMT +01:00)', 1),
('resource', 'timezone', '+10.02', 'Yakutsk Time (GMT +10:00)', 1),
('resource', 'timezone', '+6.01', 'Yekaterinburg Time (GMT +06:00)', 1)
('account','Region','1','North America'),
('account','Region','2','EMEA'),
('account','Region','3','Australia'),
('account','Region','4','ASIAPAC'),
('account','Region','5','India'),
('account','Region','6','Global'),
('account','Account Vertical',1,'Financial Services'),
('account','Account Vertical',2,'Manufacturing'),
('account','Account Vertical',3,'Healthcare'),
('account','Account Vertical',4,'Chemicals, Energy'),
('account','Account Vertical',5,'Public Sector'),
('account','Account Vertical',6,'TCG - Retail'),
('account','Account Vertical',7,'TCG - Telecom'),
('account','Account Vertical',8,'TCG - Trans & Logistics'),
('account','Primary Engagement Scope',1,'Apps incld testing only'),
('account','Primary Engagement Scope',2,'Infra only'),
('account','Primary Engagement Scope',3,'Total ITO'),
('account','Org Unit Head Designations',1,'Org Unit Head'),
('account','Org Unit Head Designations',2,'Global Account Executive'),
('account','Account Lead Designations',1,'Vertical Head'),
('account','Account Lead Designations',2,'Account Lead'),
('account','Account Lead Designations',3,'Global program Executive'),
('account','Account Status',1,'New Account in Transition'),
('account','Account Status',2,'Existing Account');

INSERT INTO `lsc_metadata_combo` (`type`, `is_active`, `adim`) VALUES
('Product Line', 1, 0),
('Region', 1, 0),
('Account Vertical', 1, 0),
('Org Unit Head Designations', 1, 0),
('Account Lead Designations', 1, 0),
('Target Date', 1, 0),
('Threshold', 1, 0),
('Attempts allowed', 1, 0),
('Overall Feedback Status', 1, 0),
('Primary Engagement Scope', 1, 0),
('Country', 1, 0),
('Time zone', 1, 0),
('Employment Status', 1, 0),
('Role', 1, 0),
('Filter option fields', 1, 0),
('KT Type', 1, 0),
('GRN Type', 1, 0),
('Status', 1, 0),
('Question Type', 1, 0),
('Category', 1, 0),
('Current role', 1, 0);